$1)$  Consider the following dynamic model:
\begin{equation}
\max_{c_t, k_{t+1}} \sum_{t=0}^{\infty} \beta^t \ln c_t \\\
\text{s.t. } k_{t+1} = k_t^\alpha - c_t, \quad t = 0, 1, \ldots
k_0 \text{ given}
\end{equation}
where all symbols have their usual meaning.

$(a)$ Set up the infinite horizon Lagrangean and take the first order condition:

\begin{equation}
L = \sum_{t=0}^{\infty} \beta^t \ln(c_t) + \sum_{t=0}^{\infty} \lambda_t [ k^{\alpha}_t - c_t - k_{t+1}]
\end{equation}

\begin{align*}
& \begin{cases}
\frac{\partial L}{\partial c_t} = 0 \\
\frac{\partial L}{\partial k_{t+1}} = 0 \\
\frac{\partial L}{\partial \lambda_t} = 0 \\
\text{transversality condition}
\end{cases}
\end{align*}


\begin{align*}
& \begin{cases}
\frac{\beta^t}{c_t} = \lambda_t \\
-\lambda_t + \lambda_{t+1} [\alpha k^{\alpha-1}_{t+1}] = 0 \\
k_{t+1} = k^{\alpha}_t - c_t \\
\lim_{t\to\infty} \frac{\beta^t}{c_t} k_{t+1} = 0
\end{cases}
\end{align*}

\begin{align*}
& \begin{cases}
\frac{\beta^t}{c_t} = \lambda_t \\
\frac{\lambda_t}{\lambda_{t+1}} = \alpha k^{\alpha-1}_{t+1} \\
c_t + k_{t+1} = k^{\alpha}_t \\
\lim_{t\to\infty} \frac{\beta^t}{c_t} k_{t+1} = 0
\end{cases}
\end{align*}


\begin{align*}
\text{since that, by the first equation we have :} \\
\frac{\beta^t}{c_t} &= \lambda_t \\
\\
\text{we can substitute it into the second equation :}
\\
\\
\frac{\lambda_t}{\lambda_{t+1}} \quad \rightarrow \quad \frac{\frac{\beta^t}{c_t}}{\frac{\beta^{t+1}}{c_{t+1}}} &
\quad \rightarrow \quad \frac{\beta^t c_{t+1}}{\beta^{t+1} c_{t}} &
\quad \rightarrow \quad \frac{c_{t+1}}{\beta c_{t}}
\end{align*}

\begin{align*}
\text{we obtain this system :     }
& \begin{cases}
\frac{\beta^t}{c_t} = \lambda_t \\
\frac{c_{t+1}}{\beta c_t} = \alpha k^{\alpha-1}_{t+1} \\
c_t + k_{t+1} = k^{\alpha}_t \\
\lim_{t\to\infty} \frac{\beta^t}{c_t} k_{t+1} = 0 \text{               (TSV cond.)}
\end{cases}
\end{align*}

\begin{align*}
\text{and so finally the key system equation :     }
& \begin{cases}
\frac{c_{t+1}}{\beta c_t} = \alpha k^{\alpha-1}_{t+1} \\
c_t + k_{t+1} = k^{\alpha}_t \\
\end{cases}
\end{align*}


$(b)$ Obtain a non linear system of 2 equations in $k_t$, $c_t$ (over and above the transversality condition)


\begin{align*}
\text{since that, by the first equation we have :} \\
\frac{\beta^t}{c_t} &= \lambda_t \\
\\
\text{we can substitute it into the second equation :}
\\
\\
\frac{\lambda_t}{\lambda_{t+1}} \quad \rightarrow \quad \frac{\frac{\beta^t}{c_t}}{\frac{\beta^{t+1}}{c_{t+1}}} &
\quad \rightarrow \quad \frac{\beta^t c_{t+1}}{\beta^{t+1} c_{t}} &
\quad \rightarrow \quad \frac{c_{t+1}}{\beta c_{t}}
\end{align*}

\begin{align*}
\text{we obtain this system :     }
& \begin{cases}
\frac{\beta^t}{c_t} = \lambda_t \\
\frac{c_{t+1}}{\beta c_t} = \alpha k^{\alpha-1}_{t+1} \\
c_t + k_{t+1} = k^{\alpha}_t \\
\lim_{t\to\infty} \frac{\beta^t}{c_t} k_{t+1} = 0 \text{               (TSV cond.)}
\end{cases}
\end{align*}

\begin{align*}
\text{and so finally the key system equation :     }
& \begin{cases}
\frac{c_{t+1}}{\beta c_t} = \alpha k^{\alpha-1}_{t+1} \\
c_t + k_{t+1} = k^{\alpha}_t \\
\end{cases}
\end{align*}


$(c)$ Briefly describe and derive the steady state of the system.


The steady state is defined as:
\begin{align*}
& \begin{cases}
k_t = k_{t+1} = k \\
c_t = c_{t+1} = c
& \end{cases}
\end{align*}

\begin{align*}
\text{so we have to rewrite in a "steady state" formulation all the variables :   } \\
& \begin{cases}
\frac{c}{\beta c} = \alpha k^{\alpha-1} \\
c + k = k^{\alpha} \\
\end{cases}
\end{align*} 

\begin{align*}
\text{and by semplifying :    } \\
& \begin{cases}
\frac{1}{\beta} = \alpha k^{\alpha-1} \\
c + k = k^{\alpha} \\
\end{cases}
\end{align*}

\begin{align*}
\text{by trying to isolate the "key" variables "c" and "k" :    } \\
& \begin{cases}
k^{\alpha-1} = \frac{1}{\alpha \beta}\\
c + k = k^{\alpha} \\
\end{cases}
\quad \rightarrow \quad
& \begin{cases}
k = \sqrt[\alpha - 1 \\\\\\\\\\\\]{\frac{1}{\alpha \beta}} \\
c = \sqrt[\alpha - 1 \\\\\\\\\\\\]{\frac{1}{\alpha \beta}}^{\\\\\\\\\\\\\\\\\  \alpha} - &
\sqrt[\alpha - 1 \\\\\\\\\\\\]{\frac{1}{\alpha \beta}}
\end{cases}
\end{align*}

\begin{align*}
\text{so these are the equations for the steady state variables :}\\
& \begin{cases}
k = \sqrt[\alpha - 1 \\\\\\\\\\\\]{\frac{1}{\alpha \beta}} \\
c = \sqrt[\alpha - 1 \\\\\\\\\\\\]{\frac{1}{\alpha \beta}}^{\\\\\\\\\\\\\\\\\  \alpha} - &
\sqrt[\alpha - 1 \\\\\\\\\\\\]{\frac{1}{\alpha \beta}}
\end{cases}
\end{align*}

$(d)$ Log linearize the two by two system

\begin{align*}
\text{and so finally the key system equation :     }
& \begin{cases}
c_{t+1} = \alpha k^{\alpha-1}_{t+1} \beta c_t\\
k_{t+1} + c_t = k^{\alpha}_t \\
\end{cases}
\end{align*}


\begin{align*}
\text{$ I) $ we first log linearize the Euler equation :     }
c_{t+1} = \alpha \beta  k^{\alpha-1}_{t+1} c_t\\
\end{align*}

\begin{align*}
\text{we take all the logs: }     
\ln{\alpha} + \ln{\beta} + \ln{c_t} + (\alpha - 1) \ln{k_{t+1}} = \ln{c_{t+1}}\\\\
\text{RHS: } \\\\
\ln{c_{t+1}}  \approx \ln{c} + \hat(c)_{t+1}\\\\
\text{LHS: } \\\\
\ln{\alpha} + \ln{\beta} + ln{c} + \hat(c)_t + (\alpha - 1) [\ln{k} + \hat(k)_{t+1}]
\end{align*}

\begin{align*}
\text{we impose LHS=RHS}\\\\
\ln{\alpha} + \ln{\beta} + ln{c} + \hat{c}_t + (\alpha - 1) [\ln{k} + \hat{k}_{t+1}] = \ln{c} + \hat{c}_{t+1}\\
\end{align*}

\begin{align*}
\text{by semplifying, we obtain the log linearization of the euler equation : }\\\\
\hat{c}_t + (\alpha - 1) \hat{k}_{t+1} = \hat{c}_{t+1}\\
\end{align*}

\begin{align*}
\text{$ II) $ now we work with the capital constraint : }\\\\
k^{\alpha}_t - c_t  = k_{t+1} \quad \rightarrow \quad &
\ln{(k^{\alpha}_t - c_t)} = \ln{(k_{t+1})}\\
\end{align*}

\begin{align*}
\text{ LHS : }
\ln{(k^{\alpha}_t - c_t)} \approx \ln{(k^\alpha - c)} + \frac{\alpha k^{\alpha - 1}}{k^\alpha - c} (k_t - k) - \frac{1}{k^\alpha - c} (c_t - c)\\\\
\text{ RHS : }
\ln{(k_{t+1})} \approx \ln{(k)} + \frac{1}{k} (k_{t+1} - k)\\\\
\text{LHS=RHS}\\
\hat{k}_{t+1} = \frac{\alpha k^{\alpha - 1}}{k^\alpha - c} (k_t - k) - \frac{1}{k^\alpha - c} (c_t - c)\\
\text{after a bit of algebra, and remembering the steady state equations ( $k^\alpha - c = k $ and $ \alpha k^{\alpha - 1} = \frac{1}{\beta} $}\\\
\text{we obtain : }
\hat{k}_{t+1} = \frac{1}{\beta} \hat{k}_t - \frac{c}{k} \hat{c}_t
\end{align*}

$(e)$ Put the system in state space

After separating the future variables ( $t+1$) from the presnt variables ( $t$) and moving the first ones to the left and the second ones to the right :

we obtain :
\begin{align}
\Gamma_0 X_{t+1} = \Gamma_1 X_{t}
\end{align}

\begin{align}
\text{where}:
X_{t}
\equiv
\begin{bmatrix}
dk_{t}\\
dc_{t}
\end{bmatrix},\quad
X_{t+1}
\equiv
\begin{bmatrix}
dk_{t+1} \\
dc_{t+1}
\end{bmatrix},\quad
\Gamma_0
\equiv
\begin{bmatrix}
1-\alpha & 1 \\
1 & 0
\end{bmatrix},\quad
\Gamma_1
\equiv
\begin{bmatrix}
0 & 1 \\
\frac{1}{\beta} & 1-\frac{1}{\beta\alpha}
\end{bmatrix} \tag{1.23}
\end{align}








$(f)$ Discuss why or why not the system can satisfy the Blanchard Khan conditions


- Firstly $\Gamma_0$ is invertible. Indeed by the codes below we can notice that the determinant of $ \Gamma_0$ is different from $0$. Hence it makes sense to check weather the Blanchard Khan are fulfilled or not. They are stated as follows:



$I)$ the matrix $P_{11}$ ($ie$ the matrix of eigen vectors corresponding to the stable eigenvalues) is invertible, then the system of difference equation has a unique solution for any given initial conditions $X_{s,t}$

$II)$ the number of unstable eigenvalues of $A$ is equal to the number of non-predetermined variables 



To check conditions : 

$I)$  it is enough to ensure that the system of difference equations has a unique solution. This easy to check, indeed it is enough to notice that if $\alpha$ is different from zero, and this is the case, there are no zero eigenvalues, hence the matrix $A$ has full rank and the system has a unique solution.


To check $II)$ :

We define the matrix $$A \equiv \Gamma_0 ^ {-1} \Gamma_1 $$
and compute its eigenvalues. 

We can easily find the two eigenvalues $\lambda_1$ and $\lambda_2$ through the determinant of the matrix $A-I\lambda$ by simply applying two important theorems.

- the determinant of a square matrix is equal to the product of its eigenvalues (and $A$ is $2x2$ hence squared)
- the trace of a square matrix is equal to the sum of its eigenvalues

After some algebra we get these two equation, that allow us to get the two desired eigenvalues.
$$\cfrac{1}{\beta} = \lambda_1 \lambda_2 \tag{1.24}$$

$$\alpha+\cfrac{1}{\alpha\beta} = \lambda_1 + \lambda_2 \tag{1.25}$$

where the LHS of the $first$ equation is the determinant of $A$ and the LHS of the $2^{nd}$ equation is its trace.

Through a system of these two equation we get $\lambda_1 = \alpha$ and $\lambda_2 = \cfrac{1}{\alpha\beta}$.

They are both non negative and we can immediatly notice that if either $\alpha$ or $\beta$ are different from one, $\lambda_2$ is larger than one, $ie$ the path of the economy is "explosive".

The number of non-predetermined variables in our model is one (capital) hence if either $\alpha$ or $\beta$ are lower than one the condition $i)$ is fulfilled. 

Finally, by putting together :

$I)$ and $II)$ we can notice that they both hold for $\alpha \neq 0$ and for any $\beta$ in the interval $[0,1]$.

$(g)$ Assume $α = 0.33$, $β = 0.98$ and write a Python Code for solving the system of
difference equation. Obtain the eigenvalues.....


\begin{align*}
\text{starting from the model in the general space representation : }
& \begin{cases}
\hat{k}_{t+1} = \frac{1}{\beta} \hat{k}_t - \frac{c}{k} \hat{c}_t \\
\hat{c}_t = \hat{c}_{t+1} - (\alpha -1) \hat{k}_{t+1}
& \end{cases}
\end{align*}

\begin{align*}
\text{anb by substituting the values of $\alpha$ and $\beta$ : }
& \begin{cases}
\hat{c}_t = \hat{c}_{t+1} + 0.67 \hat{k}_{t+1}\\
\hat{k}_{t+1} = \frac{1}{0.98} \hat{k}_t - \frac{c}{k} \hat{c}_t
& \end{cases}
\end{align*}

\begin{align*}
\text{anb by substituting the values of $\alpha$ and $\beta$ : }
& \begin{cases}
0.67 \hat{k}_{t+1} + \hat{c}_{t+1}= \hat{c}_t \\
\hat{k}_{t+1} + 0 \hat{c}_{t} = 1.02 \hat{k}_t - 2.0914 \hat{c}_t
& \end{cases}
\end{align*}

\begin{align*}
\text{where :} \frac{c}{k} = 2.0914\\
\end{align*}

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
α=0.33
β=0.98

c=(1/(α*β))**(α/(α-1)) - (1/(α*β))**(1/(α-1))
k= (1/(α*β))**(1/(α-1))

Γ0=np.asmatrix(np.zeros((2,2))) #gamma 0
Γ1=np.asmatrix(np.zeros((2,2))) #gamma

Γ0[0,0]=1-α
Γ0[0,1]=1
Γ0[1,0]=1

Γ1[0,1]=1
Γ1[1,0]=1/β
Γ1[1,1]= 1- (1/(α*β)) # or alternatively: -c/k

if np.linalg.det(Γ0)!=0:
    print('the matrix Gamma0 is invertible')
    A=np.linalg.inv(Γ0)*Γ1
    print(A)
else:
    print('the matrix \Gamma_0 is not invertible')

the matrix Gamma0 is invertible
[[ 1.02040816 -2.09214595]
 [-0.68367347  2.40173779]]


In [3]:
Γ0

matrix([[0.67, 1.  ],
        [1.  , 0.  ]])

In [4]:
Γ1

matrix([[ 0.        ,  1.        ],
        [ 1.02040816, -2.09214595]])

In [5]:
#%%
#w are the eigenvalues
#P is the matrix of eigenvector
    
w,P=np.linalg.eig(A)

print("eigenvalues",w) #blanchard conditions

eigenvalues [0.33       3.09214595]


In [6]:
#Create matrix of eigenvalues
MU=np.asmatrix(np.zeros((2,2)))
MU[0,0]=w[0] #eigenvalue 0
MU[1,1]=w[1]

#SHOULD BE AS A
AP=P*MU*np.linalg.inv(P)

print("Original Matrix A")
print (A)

print("Diagonalised Matrix A")
print(AP)

Original Matrix A
[[ 1.02040816 -2.09214595]
 [-0.68367347  2.40173779]]
Diagonalised Matrix A
[[ 1.02040816 -2.09214595]
 [-0.68367347  2.40173779]]


In [7]:
eigenValues,eigenVectors = np.linalg.eig(A)
#eigenValues is w 
#eigenVectors is v

idx = eigenValues.argsort()[::-1]  # return the index of  largest to smallest 
eigenValues = eigenValues[idx]  #sort from largest to smallets
eigenVectors = eigenVectors[:,idx]  #sort eigenvectors

if eigenValues[1] >= 1: #smallest larger than one
    print ("no saddle path, both eigenvalues larger than one")
elif eigenValues[0] <= 1: #largest smaller than
    print ("no saddle path, both eigenvalues smaller than one")
else:
    print  ("Saddle Path passed")
    print ("One eigenvalue is greater one and one is lower than one") 
    print (eigenValues)
    

Saddle Path passed
One eigenvalue is greater one and one is lower than one
[3.09214595 0.33      ]


$(h)$ What is the policy function of the linear system and what is the transition function? Obtain the numeric expressions of the two functions

In [8]:

##################################
#ASSIGN EIGENVALUES
#################################
#s are for state variables
#assign it to capital
lam_s1=eigenValues[1]  #eigenvalues in the highest index is the smallest


#u are for controls
#lam_u=MU[1,1]  #unstable eigenvalue for consumption
lam_u=eigenValues[0]  #eigenvalues in the lowest index is the largest

#Create Matrix Variable to double check
MUT=np.eye(2)
MUT[0,0]=lam_s1
MUT[1,1]=lam_u

veT=np.asmatrix(np.zeros((2,2)))
#ORDER EIGENVECTORS COHERENT WITH EIGENVALUES
veT[:,0]=eigenVectors[:,1]
veT[:,1]=eigenVectors[:,0]
WT=veT*MUT*np.linalg.inv(veT)  #shoule be identical to AP

#####################################
#MATRIX P, P^(-1) a
######################################### 
#WORK ON A TRANSFORMED MODEL
#MATRIX OF EIGENVECTOR P
P=veT
Pinv=np.linalg.inv(veT)  #P inverse
#Pinv=inv(AP)


#######################################
#TRANSFORMED VARIABLES AND PARTITION IT
#######################################
################################
#MODEL IN NOW IN TRASNFORMED FORM 
################################
#PX*_{t+1}=PINV MUT X*_{t}

P_11=np.asmatrix(np.zeros((1,1)))
P_12=np.asmatrix(np.zeros((1,1)))
P_21=np.asmatrix(np.zeros((1,1)))
P_22=np.asmatrix(np.zeros((1,1)))



P_11[0,0]=P[0,0]
P_12[0,0]=P[0,1]
P_21[0,0]=P[1,0]
P_22[0,0]=P[1,1]


Pinv_11=np.linalg.inv(P_11)

####################################
#GO BACK TO ORIGINAL VARIABLES
################################
#X_t=P * MUT^T * INV(P) * X0
######################################
k_ss=(1/(α*β))**(α/(α*β))-(1/(α*β))**(1/(α*β))

#######################################
#INITIAL CONDITIONS
#K0 GIVEN
#C0 TI ENSURE SADDLE PATH
####################################
#Fixed an Initial Level of Capital
dk0=-0.2*k_ss
#dk0=-1  
dc0=Pinv_11*P_21*dk0 #OPTIMAL INITIAL CONUMPTION TO ENSURE SADDLE PATH

###########################
#GENERATE SEQUENCE
#########################    

detP=P_11[0,0]*P_22[0,0]-P_12[0,0]*P_21[0,0]    

    
def sequence(dk0,dc0,t):
    
    dct=np.zeros(t) #zero array for consumption
    dkt=np.zeros(t) #zero array for capital
    for i in range(t):
       

        dct[i]=P_21*(lam_s1**(i+1))*(P_22*dk0-P_12*dc0)+P_22*(lam_u**(i+1))*(-P_21*dk0+P_11*dc0)
        dct[i]=dct[i]/detP
        
        
        dkt[i]=P_11*(lam_s1**(i+1))*(P_22*dk0-P_12*dc0)+P_12*(lam_u**(i+1))*(-P_21*dk0+P_11*dc0)
        dkt[i]=dkt[i]/detP
        
    
    return dct , dkt  #a list

In [9]:
#POLICY AND TRANSITION FUNCTION
POL=P_21*Pinv_11

A11=A[0,0]
A12=A[0,1]

TRANS=A11+A12*POL

print("_____________")
print("_____________")
print("policy function. X_j,t=POL*X_s,t", POL)
print("_____________")
print("_____________")




print("_____________")
print("_____________")
print("transition function:X_s,t+1=TRANS*X_s,t", TRANS)
print("_____________")
print("_____________")


_____________
_____________
policy function. X_j,t=POL*X_s,t [[0.33]]
_____________
_____________
_____________
_____________
transition function:X_s,t+1=TRANS*X_s,t [[0.33]]
_____________
_____________


$(i)$ Try to obtain the same policy and transition function using the library linearsolve

In [10]:
import linearsolve as ls
import pandas as pd


parameters = pd.Series(dtype=float)
parameters['alpha']  = 0.33
parameters['beta']  = 0.98


# Funtion that evaluates the equilibrium conditions
def equations(variables_forward,variables_current,parameters):

    # Parameters
    p = parameters
    
    #k = (1/(p.alpha * p.beta))**(1/(p.alpha -1))
    #c = (1/(p.alpha * p.beta))**(p.alpha/(p.alpha -1)) - (1/(p.alpha * p.beta))**(1/(p.alpha -1))
    

    # Variables
    fwd = variables_forward
    cur = variables_current

    # Household Euler equation
    euler_eqn= p.alpha*fwd.k**(p.alpha - 1) - fwd.c/(p.beta * cur.c)


    # Goods market clearing 
    resource_constraint = cur.c + fwd.k - (cur.k**p.alpha)

    # Stack equilibrium conditions into a numpy array
    return np.array([
            euler_eqn,
            resource_constraint,
        ])

# Initialize the model
model = ls.model(equations = equations,
                 n_states=1,
                 n_exo_states =1,
                 var_names=['k','c'],
                 parameters = parameters)

# Compute the steady state numerically
guess = [0.2,0.2]
model.compute_ss(guess) # it compute the stady state

model.approximate_and_solve() 

print("λ_1 : ", model.eig[0])
print("λ_2 : ", model.eig[1])

λ_1 :  (0.3299999999999893+0j)
λ_2 :  (3.092145949289062+0j)


In [11]:
print("Policy function: C_t = %s + K_t" % model.p)
print("Transition function: K_{t+1} = %s * K_t + C_t" % model.f)

Policy function: C_t = [[0.33]] + K_t
Transition function: K_{t+1} = [[0.33]] * K_t + C_t


$2)$ Consider the following deterministic model with leisure in the utility function:
\begin{equation}
\max_{c_t, n_t, k_{t+1}} \sum_{t=0}^{\infty} \beta^t [\ln c_t + \varphi \ln(1-n_t)]\\
\text{subject to :}\\
c_t + k_{t+1} - (1-\delta)k_t = z_t k_t^{\alpha} n_{t}^{1-\alpha}\\
k_0 \text{ given}
\end{equation}

$(a)$ Set up the Lagrangean and show that the first order conditions are:

\begin{align*}
& \begin{cases}
\frac{1}{c_t} = \frac{\beta}{c_{t+1}}[z_{t+1} \alpha k_{t+1}^{\alpha-1} n_{t+1}^{1-\alpha} + 1-\delta]\\
\frac{\phi}{1-n_t} = (1-\alpha) z_t k_t^\alpha n_t^{-\alpha}\\
\\
\text{TVC}\\
\end{cases}
\end{align*}


\begin{align*}
& \begin{cases}
\frac{1}{c_t} = \beta \frac{1}{c_{t+1}}\left[\frac{z_{t+1} \alpha k_{t+1}^{\alpha-1} n_{t+1}^{1-\alpha} + 1-\delta}{z_t}\right]\\
\frac{\phi}{1-n_t} = (1-\alpha) z_t k_t^\alpha n_t^{-\alpha}\\
\\
\text{TVC}\\
\end{cases}
\end{align*}


\begin{equation}
L = \sum_{t=0}^{\infty} \beta^t[\ln{c_t}+ \phi \ln{(1-n_t)}]+ \sum_{t=0}^{\infty} \lambda_t[z_t k^{\alpha}_t n^{1-\alpha}_t - c_t - k_{t+1} + (1 - \delta) k_t]
\end{equation}


\begin{align*}
& \begin{cases}
\frac{\partial L}{\partial c_t} = 0 \\
\frac{\partial L}{\partial n_{t}} = 0 \\
\frac{\partial L}{\partial \lambda} = 0 \\
\text{transversality condition}
\end{cases}
\end{align*}


\begin{align*}
& \begin{cases}
\frac{\beta^t}{c_t} = \lambda_t \\
-\frac{\beta^t \phi}{1-n_t} + (1- \alpha) \lambda_t z_t k^{\alpha}_t n^{-\alpha}_t = 0 \\
\lambda_t + \lambda_{t+1}[\alpha z_t k^{\alpha}_t n^{1-\alpha}_t - c_t - k_{t+1} + (1 - \delta) k_t] =0\\
z_t k^{\alpha}_t n^{1-\alpha}_t - c_t - k_{t+1} + (1 - \delta) k_t = 0 \\
\lim_{t\to\infty} \lambda_t k_{t+1} = 0  \ \ \ \ \ \text{(TVC)}
\end{cases}
\end{align*}
\
\begin{align*}
\text{now we can put our F.O.C. in a different way}
\end{align*}
\
\begin{align*}
\text{since that, by the first equation we have :} \\
\frac{\beta^t}{c_t} &= \lambda_t \\
\\
\text{we can substitute it into the second equation :}
\\
\\
\frac{\beta^t \phi}{1-n_t} - (1- \alpha) \lambda_t z_t k^{\alpha}_t n^{-\alpha} \quad \rightarrow \quad \frac{\beta^t \phi}{1-n_t} - (1- \alpha) \frac{\beta^t}{c_t} z_t k^{\alpha}_t n^{-\alpha}  &
\quad \rightarrow \quad (1- \alpha) z_t k^{\alpha}_t n^{-\alpha} = \frac{\frac{\beta^t \phi}{1-n_t}}{\frac{\beta^t}{c_t}}  & 
\quad \rightarrow \quad \frac{c_{t} \phi}{1-n_t} = (1- \alpha) z_t k^{\alpha}_t n^{-\alpha}
\end{align*}

\begin{align*}
\text{from the third equation we have :} \\
\end{align*}

\begin{align*}
\lambda_t + \lambda_{t+1}[\alpha z_{t+1} k^{\alpha-1}_{t+1} n^{1-\alpha}_{t+1} (1 - \delta)] &
\quad \rightarrow \quad \frac{\lambda_t}{\lambda^{t+1}} = [\alpha z_{t+1} k^{\alpha-1}_{t+1} n^{1-\alpha}_{t+1} (1 - \delta)] &
\quad \rightarrow \quad \frac{\frac{\beta^t}{c_t}}{\frac{\beta^{t+1}}{c_{t+1}}} = [\alpha z_{t+1} k^{\alpha-1}_{t+1} n^{1-\alpha}_{t+1} (1 - \delta)]
\end{align*}

\begin{align*}
\frac{1}{c_t} = \frac{\beta}{c_{t+1}} [\alpha z_{t+1} k^{\alpha-1}_{t+1} n^{1-\alpha}_{t+1} (1 - \delta)]
\end{align*}

\begin{align*}
\text{and so finally we obtain:}\\
& \begin{cases}
\frac{1}{c_t} = \frac{\beta}{c_{t+1}} [\alpha z_{t+1} k^{\alpha-1}_{t+1} n^{1-\alpha}_{t+1} (1 - \delta)]\\
c_t + k_{t+1} = z_t k^{\alpha}_t n^{1-\alpha}_t + (1-\alpha) k_t\\
\frac{\phi}{1-n_t}= (1-\alpha) z_t k^{\alpha}_t n^{-\alpha}_t\\
R_{t} = \alpha z_t + k^{\alpha - 1}_{t+1} n^{1 - \alpha}_t + (1-\delta)
\\
\text{TVC}\\
\end{cases}
\end{align*}

\begin{align*}
\text{and in a more compact way:}\\
& \begin{cases}
1 = \frac{\beta c_t}{c_{t+1}} [R_{t+1}]\\
c_t + k_{t+1} = z_t k^{\alpha}_t n^{1-\alpha}_t + (1 - \delta) k_t\\
\phi = c^{-1}_t (1- n_t) (1-\alpha) \frac{y_t}{n_t}\\
R_t = \alpha z_t k^{\alpha-1}_t n^{1-\alpha}_t + (1-\delta)
\end{cases}
\end{align*}



\begin{align*}
\text{our steady state is characterized by :}\\
& \begin{cases}
k_t = k_{t+1} = k\\
c_t = c_{t+1} = c\\
n_t = n_{t+1} = n\\
\end{cases}
\end{align*}


\begin{align*}
\text{and in a more compact way:}\\
& \begin{cases}
1 = \beta[r^*]\\
r^* = \alpha \frac{y^*}{k^*} +1 - \delta\\
\frac{c^*}{k^*} + \delta = \frac{y^*}{k^*}\\
y^*= k^{* 1 - \alpha} - n^{* \alpha}
\end{cases}
\end{align*}

but in a more detailed way the system result as follow :

\begin{align}
\begin{cases}
1 = \beta [z\alpha {k}^{\alpha - 1}{n}^{1 - \alpha} + 1 - \delta] \; \longrightarrow \; k = (\frac{z\alpha {n}^{1-\alpha}}{\frac{1}{\beta} - 1 + \delta})^{\frac{1}{1 - \alpha}}\\
\cfrac{\phi c}{1 - n} = (1 - \alpha)z{k}^{\alpha}{n}^{-\alpha} \\
c + \delta k = z{k}^\alpha{n}^{1-\alpha} \; \longrightarrow \; c = z{k}^\alpha{n}^{1-\alpha} - \delta k\\
\end{cases}
\end{align}


$(b)$ Log linearize the first order conditions.

We will now approximate the equations in the previous system around their steady state values by using a first order Taylor expansion after taking the logarithm of them. Please note that this process may involve a significant amount of algebra. To simplify, we assume that $z_t$ is constant and deterministic, so we can set $dz_t = 0$ at this point.

Let us start with the first equation:
\begin{align}
\frac{1}{c_t} &= \frac{\beta}{c_{t+1}} [z_{t+1}\alpha k_{t+1}^{\alpha - 1}n_{t+1}^{1-\alpha} + 1 - \delta] \
\ln{c_{t+1}} - \ln{c_t} &= \ln{\beta} +\ln{(z_{t+1}\alpha k_{t+1}^{\alpha - 1}n_{t+1}^{1-\alpha} + 1 - \delta)} \\
\end{align}

We can apply the first order Taylor approximation using the definition $dx_{t} \equiv \frac{x_{t} - x}{x}$ for $x$ in ${c,k,n}$, and obtain:


\begin{align}
dc_{t+1}-dc_t &= \ln{\beta} + \frac{z\alpha (\alpha-1)k^{\alpha-2}n^{1-\alpha}(k_{t+1}-k) + z\alpha(1-\alpha)k^{\alpha-1}n^{-\alpha}(n_{t+1}-n)} {z_{t+1}\alpha k_{t+1}^{\alpha - 1}n_{t+1}^{1-\alpha} + 1 - \delta} + \ln{(z_{t+1}\alpha k_{t+1}^{\alpha - 1}n_{t+1}^{1-\alpha} + 1 - \delta)} \\
\end{align}


We can simplify the expression by noting that $z_{t+1}\alpha k_{t+1}^{\alpha - 1}n_{t+1}^{1-\alpha} + 1 - \delta$ is equal to $1/\beta$, and $z \alpha k^{\alpha-1}n^{1-\alpha} = 1/\beta +\delta -1$.

Substituting and simplifying further, we obtain:

\begin{equation}
dc_{t+1}-dc_t = \beta (\alpha - 1) (1/\beta + \delta -1) dk_{t+1} + \beta (1-\alpha) (1/\beta + \delta -1) dn_{t+1} \\
\end{equation}

Next, consider the second equation:

\begin{equation}
\cfrac{c_t \phi}{1-n_t} = (1-\alpha)z_t {k_t}^\alpha {n_t}^{-\alpha} \\
\end{equation}

Taking the logarithm, we obtain:

\begin{equation}
\ln{\phi} + \ln{c_t} - ln{(1-n_t)} = ln{(1-\alpha)} +\ln{z_t} + \alpha \ln{k_t} - \alpha \ln{n_t} \\
\end{equation}

We can apply the first order Taylor approximation and collect terms:


Let us consider the following equation:

\begin{equation}
\ln{\left(\frac{\phi c z k^\alpha n^{-\alpha}}{(1-n)(1-\alpha)}\right)} + dc_t + \frac{n}{1-n}dc_n = \alpha(dk_t-dn_t) \\
\end{equation}

Note that in the steady state, $\phi c = (1-\alpha)(1-n)k^\alpha n^{-\alpha}$, which means that the first logarithm in the previous equation is equal to zero. Therefore, we can simplify the equation to:

\begin{equation}
dc_t + \frac{n}{1-n}dc_n = \alpha(dk_t - dn_t)\\
\end{equation}


Let's present the third equation in a different way:

Starting with this equation:
$
c_t + k_{t+1} - (1-\delta)k_t = z_t k_t^\alpha n_t^{1-\alpha} $

Taking the natural logarithm of both sides and using properties of logarithms, we get:
$ \ln(c_t + k_{t+1} - (1-\delta)k_t) = \ln(z_t) + \alpha\ln(k_t) + (1-\alpha)\ln(n_t) $

Using the first-order Taylor approximation around the steady-state values, we get:
$\ln(c + \delta k) + \cfrac{k}{c+\delta k}(c_t - c + k_{t+1} - k - (1-\delta)(k_t-k)) = \ln(z) + \alpha\ln(k) + \alpha dk_t + (1-\alpha)\ln(n) + (1-\alpha)dn_t $

Then, we can simplify and rearrange to obtain the desired form:
$\cfrac{k}{c+\delta k}dk_{t+1} = (\alpha+\cfrac{(1-\delta)k}{c+\delta k})dk_t - \cfrac{c}{c+\delta k}dc_t + (1-\alpha)dn_t $

$c)$ Write the model in State space form  and show that $A$ is not
invertible

\begin{align}
\begin{cases}
-\beta(\alpha - 1)(\frac{1}{\beta}-1+\delta)dk_{t+1} - \beta(1 - \alpha)(\frac{1}{\beta}-1+\delta)dn_{t+1} + dc_{t+1} &=  0dk_t + 0dn_t +dc_t\\
0dk_{t+1} + 0dn_{t+1} + 0dc_{t+1} &= \alpha dk_t - (\frac{n}{1-n} + \alpha)dn_t - dc_t\\
\frac {k} {c+\delta k} dk_{t+1} + 0dn_{t+1} + 0dc_{t+1} &= (\alpha + \frac {(1-\delta)k} {c+\delta k})dk_t - \frac {c}{c+\delta k} dc_t + (1-\alpha)dn_t\\
\lim_{t \to \infty} \lambda_t k_{t+1} &= 0 \\
\end{cases}
\end{align}



We can observe that the matrix $A$ is not invertible due to its elements being the coefficients of the left-hand side of the system. Additionally, its determinant is equal to zero, as one entire row consists of zeros.

$d)$ Use the Schur decomposition and explain briefly how to obtain the generalized
eigenvalues for the problem at hand

As the matrix $A$ is not invertible, we can use Schur decomposition to solve the system. Schur decomposition provides us with two orthonormal matrices, $q$ and $z$, such that $qAz = a$ and $qBz = b$, where $a$ and $b$ are upper triangular matrices. To obtain the generalized eigenvalues, we first need to find the eigenvalues of matrix $A$ and their associated eigenvectors. This will give us the eigenvector matrix, which we then orthonormalize using the Gram-Schmidt orthogonalization process to obtain the matrix $q$, with $z = q^T$. We then compute the product of $qAz$ to obtain the first upper triangular matrix $a$, and repeat the same procedure for $B$ to obtain the second upper triangular matrix $b$. Finally, we can take the ratio of the corresponding diagonal elements of the two matrices to obtain the generalized eigenvalues.

$e)$ Write a simple code with values $\phi = 0.5$, $\beta = 0.98$ and $\alpha = 0.3$ and show
numerically that the model has a unique stable steady state. For the value of $z_t$
simply assumes that is equal to 1 for any $t$.

In [12]:
# Import necessary libraries
import numpy as np      # NumPy is a library for numerical computing
import scipy.linalg as la  # SciPy is a library for scientific computing and linalg module provides linear algebra functions
import scipy            # SciPy library

# Set up the parameters
α = 0.3                # Capital share of income
β = 0.98               # Discount rate
ϕ = 0.5                # Elasticity of output with respect to capital
δ = 0.08               # Depreciation rate

n = 1/3                # Assumption: people work for a third of their day (steady-state level)

# Compute steady-state values for capital and consumption
k = ((α * (n)**(1 - α)) / ((1 / β) - 1 + δ)) ** (1 / (1 - α))     # Steady-state capital per effective worker
c = ((k)**α) * (n)**(1 - α) - δ*k      # Steady-state consumption per effective worker
#qui

In [13]:
#define the matrices A and B
A=np.asmatrix(np.zeros((3,3)))
B=np.asmatrix(np.zeros((3,3)))

A[0,0] = -β * (α - 1) * ((1 / β) - 1 + δ)
A[0,1] = -β * (1 - α) * ((1 / β) - 1 + δ)
A[0,2] = 1

A[2,0] = (k / (c + δ * k))



B[0,2] = 1

B[1,0] = α
B[1,1] = -((n / (1 - n)) - α) 
B[1,2] = -1

B[2,0] = α + (((1- δ) * k) / (c + δ * k)) 
B[2,1] = 1 - α
B[2,2] = -(c / (c + δ * k))


In [14]:
#check A invertible
np.linalg.det(A)

#it is not invertible because the determinant = 0 !!

0.0

In [15]:
#apply Schur decomposition
AA, BB, a, b, q, z = la.ordqz(A, B, sort='ouc', output='complex')

In [16]:
#generalized eigenvalues
lambda_1 = BB[0,0]/AA[0,0]
lambda_2 = BB[1,1]/AA[1,1]
lambda_3 = BB[2,2]/AA[2,2]

In [17]:
lambda_1, lambda_2, lambda_3

((0.7940312977747691+0j), (3991757883333803.5+0j), (1.2850981644236774+0j))


The generalized eigenvalues of matrices A and B can be obtained by computing the ratios of their corresponding diagonal elements, i.e., $\frac{b(i,i)}{a(i,i)}$.

To recover the unique solution of the system using Schur decomposition, we require that the number of unstable generalized eigenvalues (i.e., those with a real part greater than 1 in absolute value) is equal to the number of jumping variables.

In the current scenario, we have two jumping variables, consumption and leisure, and two unstable eigenvalues, which satisfies the required condition.

In [18]:
# Number of jumping variables
number_j = 2 # consumption, leisure
number_unstable_lambda = 2

# An array for the generalized eigenvalues
ge_eigenvalues = np.zeros(3) # number of variables

# Calculate the generalized eigenvalues by taking the real part of the ratio of the corresponding elements of matrices BB and AA
for ii in range(3):
    ge_eigenvalues[ii] = np.real(BB[ii, ii] / AA[ii, ii]) # ignore imaginary part

# Print the generalized eigenvalues
print(ge_eigenvalues)

# Check stability by looking at the absolute value of the first generalized eigenvalue
if abs(ge_eigenvalues[0]) < 1:
    print('Stable')

# Partition of z
z = np.asmatrix(z) 

# Partition z to have its stable submatrix z_11
z11 = z[0:1, 0:1]  # stable part of z
z12 = z[0:1, 1:3]
z21 = z[1:3, 0:3]  # unstable part
z22 = z[1:3, 1:3]

# Convert the partitions of z into matrices
z11 = np.asmatrix(z11)
z12 = np.asmatrix(z12)
z21 = np.asmatrix(z21)
z22 = np.asmatrix(z22)

# Invert z11
z11_inv = np.linalg.inv(z11)  
z11_inv = np.asmatrix(z11_inv)


[7.94031298e-01 3.99175788e+15 1.28509816e+00]
Stable


In [19]:
for i in ge_eigenvalues :
    print (i) #they are right ! two explosives and one <1

0.7940312977747691
3991757883333803.5
1.2850981644236774


In [20]:
#partition of a and b
a11 = AA[0:1,0:1]
b11 = BB[0:1,0:1]

a11 = np.asmatrix(a11)
b11 = np.asmatrix(b11)

#check invertibility of z11 (determiant different from zero)
np.linalg.inv(z11)

matrix([[1.20025428+0.j]])

$z_{11}$ is a scalar (different from zero) hence invertible.
The conditions for uniqness of solution are fulfilled.

$f)$ Obtain numerically the policy function and the transition function.

In [21]:
# Calculate the matrices G and H for the policy and transition functions, respectively
G = np.real(-np.linalg.inv(z22.transpose()) * z12.transpose())
H =np.real(z11 * np.linalg.inv(a11) *b11 * np.linalg.inv(z11))

# Print the policy function in the model
print("Policy Function in the Model")
print ('n_t = %.2f * k_t' % (G[0,0]))
print ('c_t = %.2f * k_t' % (G[1,0]))

# Print the transition function in the model
print("Transition Function in the Model")
print('k_t+1 = %.2f * k_t' %H )


Policy Function in the Model
n_t = -0.53 * k_t
c_t = 0.41 * k_t
Transition Function in the Model
k_t+1 = 0.79 * k_t


In [22]:
H

matrix([[0.7940313]])

(g) Try to obtain the same policy and transition function using the library linearsolve

In [26]:
import linearsolve as ls
import pandas as pd


parameters = pd.Series(dtype=float)
parameters['alpha']  = 0.3
parameters['beta']  = 0.98
parameters['delta'] = 0.2
parameters['phi'] = 0.5
parameters['z'] = 1
parameters['n'] = 1/3
parameters['k'] = k
parameters['c'] = c


# Funtion that evaluates the equilibrium conditions
def equations(variables_forward,variables_current,parameters):

    # Parameters
    p = parameters
    
     

    # Variables
    fwd = variables_forward
    cur = variables_current

    # Household Euler equation
    euler_eqn= (p.beta/fwd.c)*p.alpha*p.z*fwd.k**(p.alpha-1)*fwd.n**(1-p.alpha)+(1-p.delta) -1/cur.c
    


    # Goods market clearing 
    resource_constraint = -cur.c -fwd.k + p.z*cur.k**(p.alpha)*cur.n**(1-p.alpha) + (1-p.delta)*cur.k
    
    labor_condition = (1-p.alpha)*p.z*cur.k**p.alpha*cur.n*(-p.alpha) - (cur.c*p.phi)/(1-cur.n)

    # Stack equilibrium conditions into a numpy array
    return np.array([
            euler_eqn,
            resource_constraint,
            labor_condition
        ])

# Initialize the model
model = ls.model(equations = equations,
                 n_states=1,
                 n_exo_states =0,
                 var_names=['k','c', 'n'],
                 parameters = parameters)

# Compute the steady state numerically
guess = [1,0.2,0.2]
model.compute_ss(guess) # it compute the stady state

model.approximate_and_solve(log_linear=0) 
model.solve_klein()

print("Policy function ", model.f)
print("Transition function: ", model.p)

Policy function  [[ 0.01532143]
 [-0.06054851]]
Transition function:  [[0.81322813]]


C:\Users\Jerome Romano\AppData\Local\Temp\ipykernel_27132\1773939474.py:29: RuntimeWarning: invalid value encountered in double_scalars
  euler_eqn= (p.beta/fwd.c)*p.alpha*p.z*fwd.k**(p.alpha-1)*fwd.n**(1-p.alpha)+(1-p.delta) -1/cur.c
C:\Users\Jerome Romano\AppData\Local\Temp\ipykernel_27132\1773939474.py:34: RuntimeWarning: invalid value encountered in double_scalars
  resource_constraint = -cur.c -fwd.k + p.z*cur.k**(p.alpha)*cur.n**(1-p.alpha) + (1-p.delta)*cur.k
C:\Users\Jerome Romano\AppData\Local\Temp\ipykernel_27132\1773939474.py:36: RuntimeWarning: invalid value encountered in double_scalars
  labor_condition = (1-p.alpha)*p.z*cur.k**p.alpha*cur.n*(-p.alpha) - (cur.c*p.phi)/(1-cur.n)
C:\Users\Jerome Romano\AppData\Local\Temp\ipykernel_27132\1773939474.py:29: RuntimeWarning: invalid value encountered in double_scalars
  euler_eqn= (p.beta/fwd.c)*p.alpha*p.z*fwd.k**(p.alpha-1)*fwd.n**(1-p.alpha)+(1-p.delta) -1/cur.c
C:\Users\Jerome Romano\AppData\Local\Temp\ipykernel_27132\177393

My colleagues and I have tried unsuccessfully to achieve this point!